defaults:
  - agent/dreamer_v2
  #- env/dm_quadruped
  - env/dm_cartpole
  - _self_

seed: 42
device_type: cuda

training:
  steps: 5e5
  prefill: 1000
  pretrain: 100
  batch_size: 1024
  gradient_steps_per_step: 5
  save_checkpoint_every: 1e5
  val_logs_every: 2.5e3

validation:
  rollout_num: 5
  visualize: true

debug:
  profiler: false
