defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - training: dm
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Cartpole 4 slots, double encoder, reduced warmup, 384 n_dim, correct prev_slots, 0 nats, 40 rssm dims, 16x16 stoch
  #message: test_last
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  #prefill: 0
  #pretrain: 0
  batch_size: 16
  val_logs_every: 4e3


validation:
  rollout_num: 5
  visualize: true

#agents:
#  batch_cluster_size: 10

debug:
  profiler: false

hydra:
  mode: MULTIRUN
  #mode: RUN
  launcher:
    n_jobs: 8
  sweeper:
    params:
      agent.kl_loss_scale: 4.0,8.0,12.0,16.0,22.0,28.0,32.0,48.0
