defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - _self_

seed: 42
device_type: cuda

logger:
  message: Cartpole with discrete
  log_grads: false

training:
  checkpoint_path: null
  steps: 5e5
  prefill: 10000
  batch_size: 800
  pretrain: 100
  prioritize_ends: false
  gradient_steps_per_step: 5
  save_checkpoint_every: 2e5
  val_logs_every: 2.5e4


validation:
  rollout_num: 5
  visualize: true

debug:
  profiler: false
