defaults:
  - agent: dreamer_v2_dm
  - env: dm_quadruped
  - training: dm
  - _self_

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Quadruped, 8x, 0.25 nats, deconv, default lr, disable f16
  log_grads: false

training:
  checkpoint_path: null
  steps: 1.5e6
  val_logs_every: 5e4


validation:
  rollout_num: 5
  visualize: true

debug:
  profiler: false
