defaults:
  - agent: dreamer_v2
  - env: dm_quadruped
  - _self_

seed: 42
device_type: cuda
log_message: Quadruped with rssm

training:
  checkpoint_path: null
  steps: 1e6
  prefill: 10000
  batch_size: 800
  pretrain: 100
  prioritize_ends: false
  gradient_steps_per_step: 5
  save_checkpoint_every: 1e6
  val_logs_every: 5e3

validation:
  rollout_num: 5
  visualize: true

debug:
  profiler: false
