defaults:
  - agent: dreamer_v2
  - env: dm_quadruped
  - training: dm
  - _self_

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Quadruped with 224px input inside ViT and 16 patch size
  #message: test_last
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  batch_size: 16
  val_logs_every: 2e4


validation:
  rollout_num: 5
  visualize: true

#agents:
#  batch_cluster_size: 10

debug:
  profiler: false
