defaults:
  - agent: dreamer_v2
  - env: dm_acrobot
  - training: dm
  - _self_

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Acrobot reference with 1 nat
  log_grads: false

training:
  checkpoint_path: null
  steps: 1.5e6
  batch_size: 50
  val_logs_every: 2e4


validation:
  rollout_num: 5
  visualize: true

debug:
  profiler: false
