defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - training: dm
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

logger:
  type: null
  message: Dreamer with DINO features
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 1e3


validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.DreamerMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  #mode: MULTIRUN
  mode: RUN
  launcher:
    #n_jobs: 3
    n_jobs: 1
  sweeper:
    params:
      #agent.kl_loss_scale: 64.0,128.0,256.0
