defaults:
  - agent: dreamer_v2
  - env: dm_finger_spin
  - training: dm
  - logger: wandb
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda:0

agent:
  world_model:
    _target_: rl_sandbox.agents.dreamer.world_model_post_slot.WorldModel
    rssm_dim: 256
    slots_num: 5
    slots_iter_num: 3

    encode_vit: false
    decode_vit: false
    mask_combination: soft
    vit_l2_ratio: 1.0

    vit_img_size: 224
    kl_loss_scale: 1.0
    kl_loss_balancing: 0.8
    kl_free_nats: 1.0

    use_reshuffle: true
    per_slot_rec_loss: true

  wm_optim:
    lr_scheduler:
      - _target_: rl_sandbox.utils.optimizer.WarmupScheduler
        _partial_: true
        warmup_steps: 1e3

logger:
  message: Post-wm slot attention, per slot rec, finger spin, n_dim=256, state_feature=5, slots=5
  log_grads: false

training:
  f16_precision: false
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 2e4

validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.PostSlottedDreamerMetricsEvaluator
      _partial_: true
    #- _target_: rl_sandbox.crafter_metrics.CrafterMetricsEvaluator
    #  _partial_: true

debug:
  profiler: false

hydra:
  #mode: MULTIRUN
  mode: RUN
  launcher:
    n_jobs: 1
  #  n_jobs: 8
  #sweeper:
  #  params:
  #    agent.world_model.kl_loss_scale: 1e-3,5e-3,1e-2,5e-2,5,10,15,20,25,50,75,100,250
  #    agent.world_model.full_qk_from: 1,2e4
  #    agent.world_model.symmetric_qk: true,false
  #    agent.world_model.attention_block_num: 1,3
