defaults:
  - agent: dreamer_v2
  - env: dm_quadruped
  - _self_

seed: 42
device_type: cuda

training:
  steps: 2e6
  prefill: 1000
  pretrain: 100
  batch_size: 400
  gradient_steps_per_step: 5
  save_checkpoint_every: 1e5
  val_logs_every: 5e3

validation:
  rollout_num: 5
  visualize: true

env:
  obs_res: [128, 128]

debug:
  profiler: false
