defaults:
  - agent: dreamer_v2_atari
  - env: atari_freeway
  - training: atari
  - logger: tensorboard
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

logger:
  message: Atari with default dreamer
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 2e4

validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.DreamerMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  mode: MULTIRUN
  #mode: RUN
  launcher:
    n_jobs: 8
  sweeper:
    params:
      env.task_name: amidar,asterix,chopper_command,demon_attack,freeway,private_eye,venture,video_pinball
