defaults:
  - agent: dreamer_v2
  - env: dm_acrobot
  - training: dm
  - logger: wandb
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

agent:
  world_model:
    _target_: rl_sandbox.agents.dreamer.world_model_post_slot.WorldModel
    rssm_dim: 256
    slots_num: 5
    slots_iter_num: 3

    encode_vit: false
    decode_vit: true
    mask_combination: soft
    vit_l2_ratio: 1.0

    vit_img_size: 224
    kl_loss_scale: 1.0
    kl_loss_balancing: 0.8
    kl_free_nats: 1.0

    use_reshuffle: true
    per_slot_rec_loss: false
    spatial_decoder: false

  wm_optim:
    lr_scheduler:
      - _target_: rl_sandbox.utils.optimizer.WarmupScheduler
        _partial_: true
        warmup_steps: 1e3

logger:
  message: Post-wm dino slot attention, n_dim=256
  log_grads: false

training:
  f16_precision: true
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 2e4

validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.PostSlottedDinoDreamerMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  #mode: MULTIRUN
  mode: RUN
  launcher:
    n_jobs: 3
  sweeper:
    params:
      seed: 17,42,45
      env: dm_finger_spin,dm_finger_turn_hard

