defaults:
  - agent: dreamer_v2_slotted_combined
  - env: crafter
  - training: crafter
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Crafter combined slotted 10x reconstruction
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 5e3

validation:
  rollout_num: 3
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.SlottedDreamerMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  mode: MULTIRUN
  #mode: RUN
  launcher:
    n_jobs: 8
  sweeper:
    params:
      agent.world_model.per_slot_rec_loss: true
      agent.world_model.mask_combination: soft
      agent.world_model.kl_loss_scale: 1e2,1e4
      agent.world_model.vit_l2_ratio: 0.1,0.01,0.9,0.99
