defaults:
  - agent: dreamer_v2_slotted_attention
  - env: crafter
  - training: crafter
  - logger: wandb
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda:0

agent:
  world_model:
    encode_vit: false
    decode_vit: true
    vit_img_size: 224
    vit_l2_ratio: 1.0
    slots_iter_num: 3
    slots_num: 4
    kl_loss_scale: 3.0
    kl_loss_balancing: 0.6
    kl_free_nats: 1.0

  actor_optim:
    lr: 1e-4

  critic_optim:
    lr: 1e-4

logger:
  message: Attention, only dino, kl=0.6/3, 14x14, 768 rssm, no fp16, reverse dino
  log_grads: false

training:
  f16_precision: false
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 2e4

validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.SlottedDinoDreamerMetricsEvaluator
    #- _target_: rl_sandbox.metrics.SlottedDreamerMetricsEvaluator
      _partial_: true
    - _target_: rl_sandbox.crafter_metrics.CrafterMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  #mode: MULTIRUN
  mode: RUN
  launcher:
    n_jobs: 1
  #  n_jobs: 8
  #sweeper:
  #  params:
  #    agent.world_model.full_qk_from: 1,2e4
  #    agent.world_model.symmetric_qk: true,false
  #    agent.world_model.attention_block_num: 1,3
