defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - training: dm
  - logger: wandb
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

agent:
  world_model:
    _target_: rl_sandbox.agents.dreamer.world_model.WorldModel
    rssm_dim: 200

    encode_vit: false
    decode_vit: false
    #vit_l2_ratio: 1.0

    #kl_loss_scale: 2.0
    #kl_loss_balancing: 0.8
    #kl_free_nats: 1.0

  #wm_optim:
  #  lr_scheduler:
  #    - _target_: rl_sandbox.utils.optimizer.WarmupScheduler
  #      _partial_: true
  #      warmup_steps: 1e3

logger:
  message: Default dreamer fp16
  log_grads: false

training:
  f16_precision: true
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 2e4

validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.DreamerMetricsEvaluator
      _partial_: true
    #- _target_: rl_sandbox.metrics.PostSlottedDreamerMetricsEvaluator
    #  _partial_: true
    #- _target_: rl_sandbox.crafter_metrics.CrafterMetricsEvaluator
    #  _partial_: true

debug:
  profiler: false

hydra:
  mode: MULTIRUN
  #mode: RUN
  launcher:
    n_jobs: 3
  sweeper:
    params:
      seed: 17,42,45
      env: dm_finger_spin,dm_finger_turn_hard
