defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - training: dm
  - _self_

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Cartpole 8 slots, reduced warmup, 192 n_dim, correct prev_slots, 8x KL, 0 nats, 40 rssm dims, 16x16 stoch
  #message: test_last
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  #prefill: 0
  #pretrain: 0
  batch_size: 16
  val_logs_every: 1e2


validation:
  rollout_num: 5
  visualize: true

#agents:
#  batch_cluster_size: 10

debug:
  profiler: false
