defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - training: dm
  - _self_

seed: 42
device_type: cuda

logger:
  type: tensorboard
  message: Cartpole with convolutional decoder
  #message: test_last
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  batch_size: 50
  val_logs_every: 2e4
  #val_logs_every: 2.5e3


validation:
  rollout_num: 5
  visualize: true

debug:
  profiler: false
