defaults:
  - agent: dreamer_v2_slotted_attention
  - env: crafter
  - training: crafter
  - logger: wandb
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda:0

agent:
  world_model:
    encode_vit: false
    decode_vit: false
    #vit_img_size: 224
    #vit_l2_ratio: 0.5
    slots_iter_num: 3
    slots_num: 6
    kl_loss_scale: 1.0
    kl_free_nats: 1.0

logger:
  message: Attention, without dino, fixed KL, 1 nat, no prev slot
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  val_logs_every: 2e4

validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    #- _target_: rl_sandbox.metrics.SlottedDinoDreamerMetricsEvaluator
    - _target_: rl_sandbox.metrics.SlottedDreamerMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  #mode: MULTIRUN
  mode: RUN
  launcher:
    n_jobs: 1
  #  n_jobs: 8
  #sweeper:
  #  params:
  #    agent.world_model.full_qk_from: 1,2e4
  #    agent.world_model.symmetric_qk: true,false
  #    agent.world_model.attention_block_num: 1,3
