defaults:
  - agent: dreamer_v2_slotted
  - env: dm_cartpole
  - training: dm
  - _self_
  - override hydra/launcher: joblib

seed: 42
device_type: cuda

logger:
  type: null
  message: Cartpole 2 slots, double encoder, reduced warmup, 384 n_dim, correct prev_slots, 0.05 nats, 40 rssm dims, 16x16 stoch, 2x KL
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  prefill: 0
  pretrain: 1
  batch_size: 2
  val_logs_every: 1e3


validation:
  rollout_num: 5
  visualize: true
  metrics:
    - _target_: rl_sandbox.metrics.EpisodeMetricsEvaluator
      log_video: True
      _partial_: true
    - _target_: rl_sandbox.metrics.SlottedDreamerMetricsEvaluator
      _partial_: true

debug:
  profiler: false

hydra:
  #mode: MULTIRUN
  mode: RUN
  launcher:
    #n_jobs: 3
    n_jobs: 1
  sweeper:
    params:
      #agent.kl_loss_scale: 64.0,128.0,256.0
