defaults:
  - agent: dreamer_v2
  - env: dm_cartpole
  - training: dm
  - _self_

seed: 42
device_type: cuda

logger:
  type: null
  message: Cartpole with only 1 slot without KL
  #message: test_last
  log_grads: false

training:
  checkpoint_path: null
  steps: 1e6
  #prefill: 0
  pretrain: 0
  batch_size: 16
  val_logs_every: 2.5e3


validation:
  rollout_num: 5
  visualize: true

#agents:
#  batch_cluster_size: 10

debug:
  profiler: false
