defaults:
  - dreamer_v2
  - _self_

clip_rewards: tanh
layer_norm: true

world_model:
  rssm_dim: 1024
  predict_discount: true

actor:
  entropy_scale: 3e-3

critic:
  discount_factor: 0.999

wm_optim:
  lr: 1e-4

actor_optim:
  lr: 1e-4

critic_optim:
  lr: 1e-4
