defaults:
  - dreamer_v2
  - _self_

clip_rewards: tanh
layer_norm: true

world_model:
  rssm_dim: 600
  kl_loss_scale: 0.1
  discount_loss_scale: 5.0
  predict_discount: true

actor:
  entropy_scale: 1e-3

critic:
  discount_factor: 0.999

wm_optim:
  lr: 2e-4

actor_optim:
  lr: 4e-5

critic_optim:
  lr: 1e-4
