_target_: rl_sandbox.utils.env.DmEnv
domain_name: cartpole
task_name: swingup
run_on_pixels: true
obs_res: [64, 64]
transforms: 
  - _target_: rl_sandbox.utils.env.ActionNormalizer
  - _target_: rl_sandbox.utils.env.ActionDisritezer
    actions_num: 10
