defaults:
  - agent/dreamer_v2
  - env/dm_cartpole
  - _self_

seed: 42
device_type: cpu

training:
  epochs: 5000
  batch_size: 64
  gradient_steps_per_step: 4
  save_checkpoint_every: 1000
  val_logs_every: 5

validation:
  rollout_num: 5
  visualize: true
