defaults:
  - agent/dreamer_v2
  - _self_

env:
  # type: gym
  # name: CartPole-v1
  type: dm_control
  domain_name: cartpole
  task_name: swingup
  run_on_pixels: true
  obs_res: [64, 64]

seed: 42
device_type: cpu

training:
  epochs: 5000
  batch_size: 128

validation:
  rollout_num: 5
  visualize: true
