_target_: rl_sandbox.agents.DreamerV2
# World model parameters
batch_cluster_size: 8
latent_dim: 32
latent_classes: 32
rssm_dim: 200 
kl_loss_scale: 0.1

# ActorCritic parameters
imagination_horizon: 15
discount_factor: 0.995
#critic_update_interval: 100
