_target_: rl_sandbox.utils.env.DmEnv
domain_name: cartpole
task_name: swingup
run_on_pixels: true
obs_res: [64, 64]
camera_id: 0
repeat_action_num: 2
transforms: 
  - _target_: rl_sandbox.utils.env.ActionNormalizer
